#!/usr/bin/env ruby

require "thor"
require "open3"
require_relative "pco_apps"
require_relative "post_to_slack"
require_relative "pco_box"

class WorkDay < Thor
  include Thor::Actions

  package_name "WorkDay"

  class_option(:skip_slack, type: :boolean, aliases: :s, desc: "Whether to send a message to Slack or not. Default is to send a message.")

  desc "start", "Start up your PCO workday"
  option(:skip_update_box, type: :boolean, aliases: :b, desc: "Whether to update pco-box or not. Default is to update.")
  option(:skip_update_apps, type: :boolean, aliases: :a, desc: "Whether to update apps or not. Default is to update.")
  option(:run_webpack, type: :boolean, aliases: :w, desc: "Whether to run webpack when updating apps or not. Default is to skip it.")
  def start
    PostToSlack.start_day unless options[:skip_slack]
    PcoApps.before_update unless options[:skip_update_apps]
    PcoBox.update unless options[:skip_update_box]
    PcoBox.update_apps(options[:run_webpack]) unless options[:skip_update_apps]
    PcoApps.after_update unless options[:skip_update_apps]
    PcoBox.start if options[:skip_update_box] && options[:skip_update_apps]
  end

  desc "end", "End your PCO workday"
  option(:skip_box_stop, type: :boolean, aliases: :b, desc: "Whether to stop pco-box or not. Default is to stop.")
  def end
    PostToSlack.end_day unless options[:skip_slack]
    PcoBox.stop unless options[:skip_box_stop]
    # offer to wip commit uncommitted work?
    # offer to push up branch to github if it's not already?
  end
end

WorkDay.start(ARGV)
